baseURL = 'https://kx06.github.io'
languageCode = 'en-us'
title = "Krishhh16"

pagination.pagerSize = 10

[params]
description = "Personal blog, DSA Writeups, Occasioanl HOW TOs maybe ?"
dateFormat = "2 Jan, 2006"

[markup]
  [markup.highlight]
    style = 'onedark'


[taxonomies]
category = "categories"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
